services:
  postgres:
    image: postgres:15-alpine
    container_name: nyc-taxi-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-nyc_taxi}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Script d'initialisation optionnel
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-nyc_taxi}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - nyc-taxi-network

  mongodb:
    image: mongo:7
    container_name: nyc-taxi-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-admin}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-nyc_taxi_clean}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: >
      mongod 
      --quiet 
      --bind_ip_all
      --logpath /dev/null
      --logappend
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - nyc-taxi-network
    logging:
      driver: "none"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nyc-taxi-app
    environment:
      # Configuration PostgreSQL
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-nyc_taxi}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      
      # Configuration de l'application
      APP_ENV: ${APP_ENV:-development}
      API_HOST: ${API_HOST:-0.0.0.0}
      API_PORT: ${API_PORT:-8000}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      
      # Configuration des données
      DATA_DIR: /app/data
      RAW_DATA_DIR: /app/data/raw
      
      # Configuration du traitement par chunks
      CHUNK_SIZE: ${CHUNK_SIZE:-25000}
    ports:
      - "8000:8000"
    volumes:
      # Montage des données pour l'accès aux fichiers Parquet (lecture/écriture)
      - ./data:/app/data
      # Montage du code source pour le développement (hot reload)
      - ./src:/app/src:ro
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    command: >
      sh -c "
        echo '🚀 Démarrage du pipeline NYC Taxi Data...' &&
        echo '📁 Étape 1: Vérification des répertoires...' &&
        python scripts/ensure_directories.py &&
        echo '📊 Étape 2: Vérification des bases de données...' &&
        python scripts/wait_for_db.py &&
        echo '📥 Étape 3: Téléchargement des données...' &&
        python src/download_data.py &&
        echo '💾 Étape 4: Import PostgreSQL (avec déduplication)...' &&
        python src/import_to_postgres.py &&
        echo '🔄 Étape 5: Nettoyage et import MongoDB...' &&
        python scripts/wait_for_mongodb.py &&
        python src/data_cleaner.py &&
        echo '🌐 Étape 6: Démarrage de l application FastAPI...' &&
        uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
      "
    restart: unless-stopped
    networks:
      - nyc-taxi-network

  # Service optionnel pour l'import des données
  data-importer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nyc-taxi-importer
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-nyc_taxi}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      DATA_DIR: /app/data
      RAW_DATA_DIR: /app/data/raw
    volumes:
      - ./data:/app/data:ro
      - ./src:/app/src:ro
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        python scripts/wait_for_db.py &&
        echo 'Import des données...' &&
        python src/import_to_postgres.py
      "
    profiles:
      - import  # Service activé uniquement avec --profile import
    networks:
      - nyc-taxi-network

volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local

networks:
  nyc-taxi-network:
    driver: bridge
