name: Semantic Release

on:
  push:
    branches: [ main, develop, 'feature/*' ]
  pull_request:
    branches: [ main, develop ]   # (PR = dry-run éventuel, pas de vrai release)

jobs:
  release:
    # Ne release que sur push (pas PR) et sur branches autorisées
    if: >
      github.event_name == 'push' &&
      (startsWith(github.ref, 'refs/heads/main') ||
       startsWith(github.ref, 'refs/heads/develop') ||
       startsWith(github.ref, 'refs/heads/feature/'))
    runs-on: ubuntu-latest
    concurrency: release-${{ github.ref }}
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}       # évite le detached HEAD

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"       # aligne avec requires-python >=3.13

      - name: Initialize uv.lock if missing
        run: |
          if [ ! -f uv.lock ]; then
            uv lock
          fi

      - name: Install dependencies
        run: uv pip install --system python-semantic-release

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release --verbose version --changelog
          semantic-release --verbose publish
